module.exports = [
  {
    scenarioId: "APPENDICITIS_AFTER_WAIT",
    title: "Emergency appendicitis after waiting period",
    ruleSetId: "STANDARD_HEALTH",
    description: "A newly occurring condition with matching hospital evidence.",
    input: {
      policyStartOffsetDays: -120,
      incidentOffsetDays: -2,
      claimType: "SURGERY",
      claimAmountEth: "0.20",
      coverageAmountEth: "1.00",
      preExistingCondition: false,
      disclosedAtPurchase: false,
    },
    expectedOutcome: "PARTIAL_BENEFIT",
  },
  {
    scenarioId: "ROAD_ACCIDENT_IMMEDIATE",
    title: "Road accident shortly after purchase",
    ruleSetId: "ACCIDENT_EMERGENCY",
    description: "An accidental emergency covered without an initial waiting period.",
    input: {
      policyStartOffsetDays: -3,
      incidentOffsetDays: -1,
      claimType: "ACCIDENT",
      claimAmountEth: "0.25",
      coverageAmountEth: "1.00",
      preExistingCondition: false,
      disclosedAtPurchase: false,
    },
    expectedOutcome: "PARTIAL_BENEFIT",
  },
  {
    scenarioId: "EARLY_HOSPITALIZATION_WAIT",
    title: "Hospitalization during initial waiting period",
    ruleSetId: "STANDARD_HEALTH",
    description: "A non-emergency hospitalization occurring too early in the policy term.",
    input: {
      policyStartOffsetDays: -10,
      incidentOffsetDays: -1,
      claimType: "HOSPITALIZATION",
      claimAmountEth: "0.10",
      coverageAmountEth: "1.00",
      preExistingCondition: false,
      disclosedAtPurchase: false,
    },
    expectedOutcome: "WAITING_PERIOD",
  },
  {
    scenarioId: "DISCLOSED_PRE_EXISTING_CONDITION",
    title: "Disclosed pre-existing condition",
    ruleSetId: "STANDARD_HEALTH",
    description: "A disclosed condition is routed to review while its special wait is checked.",
    input: {
      policyStartOffsetDays: -180,
      incidentOffsetDays: -1,
      claimType: "HOSPITALIZATION",
      claimAmountEth: "0.15",
      coverageAmountEth: "1.00",
      preExistingCondition: true,
      disclosedAtPurchase: true,
    },
    expectedOutcome: "WAITING_PERIOD",
  },
  {
    scenarioId: "UNDISCLOSED_PRE_EXISTING_CONDITION",
    title: "Undisclosed pre-existing condition",
    ruleSetId: "CRITICAL_ILLNESS",
    description: "Non-disclosure is flagged for human review instead of silently auto-rejecting.",
    input: {
      policyStartOffsetDays: -800,
      incidentOffsetDays: -1,
      claimType: "CANCER",
      claimAmountEth: "0.50",
      coverageAmountEth: "1.00",
      preExistingCondition: true,
      disclosedAtPurchase: false,
    },
    expectedOutcome: "MANUAL_REVIEW",
  },
  {
    scenarioId: "COSMETIC_EXCLUSION",
    title: "Excluded cosmetic procedure",
    ruleSetId: "STANDARD_HEALTH",
    description: "The submitted treatment category is explicitly excluded by the policy terms.",
    input: {
      policyStartOffsetDays: -400,
      incidentOffsetDays: -1,
      claimType: "COSMETIC",
      claimAmountEth: "0.30",
      coverageAmountEth: "1.00",
      preExistingCondition: false,
      disclosedAtPurchase: false,
    },
    expectedOutcome: "EXCLUDED",
  },
];
